name: Run Python Tests
on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: openmpi
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Cython
          wget https://pypi.python.org/packages/41/7a/6048de44c62fc5e618178ef9888850c3773a9e4be249e5e673ebce0402ff/h5py-2.7.1.tar.gz
          tar zxvf h5py-2.7.1.tar.gz
          cd h5py-2.7.1
          export CC=mpicc
          python setup.py configure --mpi
          python setup.py install
      - name: Run test Linalg 
        run:  pytest test_linalg.py
      - name: Run test Lattice
        run:  python test_lattice.py
      - name: Run test LatticeEO
        run:  python test_lattice_EO.py    
      - name: Run test MPI Lattice 
        run:  mpiexec -n 2 python test_lattice_mpi.py
      - name: Run test MPI IO  
        run:  mpiexec -n 4 python test_mpi_io.py
        
      
