name: Run Python Tests
on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mpi4py/setup-mpi@v1
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test2
        run: pytest test_lattice.py  
      - name: Run test1 
        run:  pytest test_linalg.py
      - name: Run MPI tests
        run:  mpiexec -n 2 manual_test_mpi.py
      
